theme: jekyll-theme-architect
show_downloads: false
title: Microâ€†Frontends
description: extending the microservice idea to frontend development
github:
  is_project_page: true
  repository_url: https://github.com/neuland/micro-frontends
exclude:
  - 2-composition-universal
  - 3-data-fetching
  - node_modules
